name: movie_db
description: To integrate all sorts of features provided by MovieDB website

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get:
  dio: ^3.0.10
  cupertino_icons: ^1.0.2
  google_fonts: ^1.1.2
  get_it: ^5.0.6
  flutter_bloc: ^6.1.2
  equatable: ^1.2.6
  dartz: ^0.9.2
  shared_preferences: ^0.5.12+4
  cached_network_image: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^4.1.4

flutter:
  uses-material-design: true

assets:
  - assets/
